/*
2) Escreva uma consulta SQL para retornar dados únicos conforme tabela abaixo.
Caso o aluno tenha mais de dois responsáveis, traga apenas os dois primeiros
responsáveis encontrados na tabela.
*/

SELECT A.NOME AS ALUNO,
    (SELECT R1.NOME FROM RESPONSAVEL R1 INNER JOIN PARENTESCO P ON P.IDALUNO = A.ID WHERE A.ID = P.IDALUNO LIMIT 1) AS RESPONSAVEL,
    (SELECT P1.PARENTESCO FROM PARENTESCO P1 WHERE P1.IDALUNO = A.ID LIMIT 1) AS PARENTESCO,
    (SELECT R.NOME FROM RESPONSAVEL R INNER JOIN PARENTESCO P ON P.IDALUNO = A.ID WHERE A.ID = P.IDALUNO 
    AND R.NOME != (SELECT R1.NOME FROM RESPONSAVEL R1 INNER JOIN PARENTESCO P ON P.IDALUNO = A.ID WHERE A.ID = P.IDALUNO LIMIT 1) LIMIT 1) AS RESPONSAVEL,
    (SELECT P.PARENTESCO FROM PARENTESCO P WHERE P.IDALUNO = A.ID 
    AND P.PARENTESCO != (SELECT P1.PARENTESCO FROM PARENTESCO P1 WHERE P1.IDALUNO = A.ID LIMIT 1) LIMIT 1) AS PARENTESCO
FROM ALUNO A;
